knpu_oauth2_client:
    clients:
        bitbucket:
            type: bitbucket
            client_id: '%env(OAUTH_BITBUCKET_CLIENT_ID)%'
            client_secret: '%env(OAUTH_BITBUCKET_CLIENT_SECRET)%'
            redirect_route: oauth_bitbucket
            redirect_params: {}
            #use_state: true
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
            redirect_route: oauth_github
            redirect_params: {}
            #use_state: true
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: oauth_google
            redirect_params: {}
            #access_type: null
            #hosted_domain: null
            #user_fields: {}
            #use_oidc_mode: false
            #use_state: true
