framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - eTraxis\MessageBus\Middleware\HttpExceptionMiddleware
                    - eTraxis\MessageBus\Middleware\TimingMiddleware
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - eTraxis\MessageBus\Middleware\HttpExceptionMiddleware
                    - eTraxis\MessageBus\Middleware\TimingMiddleware
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - eTraxis\MessageBus\Middleware\HttpExceptionMiddleware
                    - eTraxis\MessageBus\Middleware\TimingMiddleware
                    - validation
                    - doctrine_transaction

services:

    _defaults:
        autowire: true
        autoconfigure: false

    eTraxis\Application\Command\:
        resource: '%kernel.project_dir%/src/Application/Command/*/Handler/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: command.bus }]

    eTraxis\Application\Query\:
        resource: '%kernel.project_dir%/src/Application/Query/*/Handler/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: query.bus }]

    eTraxis\Application\Event\:
        resource: '%kernel.project_dir%/src/Application/Event/*/Subscriber/*.php'
        tags: [{ name: messenger.message_handler, bus: event.bus }]
