security:

    encoders:
        eTraxis\Entity\User: auto
        legacy.md5:
            id: eTraxis\Security\Encoder\Md5PasswordEncoder
        legacy.sha1:
            id: eTraxis\Security\Encoder\Sha1PasswordEncoder

    providers:
        etraxis_provider:
            id: etraxis.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_doc:
            pattern:  ^/api/(doc|doc\.json)$
            security: false
        main:
            anonymous:    lazy
            logout:       true
            user_checker: LazySec\Checker\GenericUserChecker
            switch_user:  { role: ROLE_ADMIN }
            guard:
                authenticators:
                    - eTraxis\Security\Authenticator\DatabaseAuthenticator
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000
                path:     /

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,      roles: ROLE_USER                    }
