security:

    encoders:
        eTraxis\Entity\User: auto
        legacy.md5:
            id: eTraxis\Security\Encoder\Md5PasswordEncoder
        legacy.sha1:
            id: eTraxis\Security\Encoder\Sha1PasswordEncoder

    providers:
        etraxis_provider:
            id: LazySec\Provider\GenericUserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_doc:
            pattern:  ^/api/(doc|doc\.json)$
            security: false
        main:
            pattern:  ^/api
            security: true
            guard:
                authenticators:
                    - eTraxis\Security\Authenticator\EmptyAuthenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/, roles: ROLE_USER }
