nelmio_api_doc:
    documentation:
        info:
            title: eTraxis
            description: API Reference Guide
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
