parameters:

    env(MAILER_FROM): ~

    env(ETRAXIS_LOCALE): en

services:

    _defaults:
        autowire: true
        autoconfigure: true

    eTraxis\:
        resource: '../src/*'
        exclude: '../src/{Application,Doctrine,Entity,Migrations,Kernel.php}'

    eTraxis\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # autowiring hints
    eTraxis\Subscriber\MessageSender:
        $sender: '%env(MAILER_FROM)%'
