parameters:

    env(MAILER_FROM): ~

    env(ETRAXIS_LOCALE): en_US
    env(ETRAXIS_THEME):  azure

    env(ETRAXIS_AUTH_FAILURES): ~
    env(ETRAXIS_LOCK_DURATION): ~

    env(LDAP_URL):    ~
    env(LDAP_BASEDN): ~

    env(OAUTH_GOOGLE_CLIENT_ID):     ~
    env(OAUTH_GOOGLE_CLIENT_SECRET): ~

    env(OAUTH_GITHUB_CLIENT_ID):     ~
    env(OAUTH_GITHUB_CLIENT_SECRET): ~

    env(OAUTH_BITBUCKET_CLIENT_ID):     ~
    env(OAUTH_BITBUCKET_CLIENT_SECRET): ~

    oauth.google.client.id:    '%env(OAUTH_GOOGLE_CLIENT_ID)%'
    oauth.github.client.id:    '%env(OAUTH_GITHUB_CLIENT_ID)%'
    oauth.bitbucket.client.id: '%env(OAUTH_BITBUCKET_CLIENT_ID)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    eTraxis\:
        resource: '../src/*'
        exclude: '../src/{Application,Doctrine,Entity,Migrations,Kernel.php}'

    eTraxis\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # autowiring hints
    eTraxis\DataFixtures\ProductionFixtures:
        $locale: '%env(ETRAXIS_LOCALE)%'
        $theme:  '%env(ETRAXIS_THEME)%'

    # autowiring hints
    eTraxis\Repository\FileRepository:
        $storage: '%env(FILES_STORAGE)%'

    # autowiring hints
    eTraxis\Security\Authenticator\LdapAuthenticator:
        $url:    '%env(LDAP_URL)%'
        $basedn: '%env(LDAP_BASEDN)%'

    # autowiring hints
    eTraxis\Subscriber\MessageSender:
        $sender: '%env(MAILER_FROM)%'

    # autowiring hints
    eTraxis\Subscriber\StickyLocale:
        $locale: '%env(ETRAXIS_LOCALE)%'

    # autowiring hints
    eTraxis\Voter\IssueVoter:
        $maxsize: '%env(FILES_MAXSIZE)%'
