parameters:

    env(MAILER_FROM): ~

    env(ETRAXIS_LOCALE): en

    env(LDAP_URL):    ~
    env(LDAP_BASEDN): ~

    env(OAUTH_GOOGLE_CLIENT_ID):     ~
    env(OAUTH_GOOGLE_CLIENT_SECRET): ~

    oauth.google.client.id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    eTraxis\:
        resource: '../src/*'
        exclude: '../src/{Application,Doctrine,Entity,Migrations,Kernel.php}'

    eTraxis\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # autowiring hints
    eTraxis\Security\Authenticator\LdapAuthenticator:
        $url:    '%env(LDAP_URL)%'
        $basedn: '%env(LDAP_BASEDN)%'

    # autowiring hints
    eTraxis\Subscriber\MessageSender:
        $sender: '%env(MAILER_FROM)%'
